<?php

/**
 * Stetic Analytics Magento Extension
 *
 * @category    Stetic
 * @package     Stetic_Analytics
 * @copyright   Copyright (c) 2014 Stetic (http://www.stetic.com/)
 * @license     http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 */
if($this->isEnabled()) { ?>
<script type="text/javascript">
var _fss=_fss||{}; _fss.token = '<?php echo $this->getSiteToken(); ?>';
<?php if($this->getCookieDomain()) { ?>_fss.cookieDomain = '<?php echo $this->getCookieDomain(); ?>';<?php } ?>
<?php echo $this->identify(); ?>
(function(){var e="stetic",a=window,c=["track","identify","config","register","unregister"],b=function(){var d=0,f=this;for(f._fs=[],d=0;c.length>d;d++){(function(j){f[j]=function(){return f._fs.push([j].concat(Array.prototype.slice.call(arguments,0))),f}})(c[d])}};a[e]=a[e]||new b;a.fourstats=a.fourstats||new b;var i=document;var h=i.createElement("script");h.type="text/javascript";h.async=true;h.src="//stetic.com/t.js";var g=i.getElementsByTagName("script")[0];g.parentNode.insertBefore(h,g)})();
<?php echo $this->trackEvents(); ?>
</script>
<?php
}
